OBAAS/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('homeApp.urls')),
    url(r'^home/', include('homeApp.urls')),
    url(r'^bank/', include('bankApp.urls')),
]

bankApp/urls.py
from django.conf.urls import url
from . import views

# Defining URL pattenrs to route different views on the site
app_name = 'bank'
urlpatterns = [
    url(r'^account-balance/$', views.checkBalance, name='account-balance'),
    url(r'^service-request/$', views.serviceRequest, name='service-request'),
    url(r'^pay-bill/$', views.payBill, name='pay-bill'),
    url(r'^close-account/$', views.closeAccount, name='close-account'),
    url(r'^create-account/$', views.createAccount, name='create-account'),
]

homeApp/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

homeApp/models.py
from django.db import models

# Create your models here.

homeApp/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'home/index.html')

homeApp/templates/home/footer.html
<!-- Page footer. Consistent across all the pages in the website -->
<footer class="page_footer">
		 &copy; Copyright BrisbaneParks.com
</footer>

homeApp/templates/home/header.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}OBAAS{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'home/CSS/main.css' %}"/>
    <script src="{% static 'home/JS/nav-menu.js' %}"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
  <div id="mySidenav" class="sidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <a href="{% url 'bank:account-balance' %}">Account Balance</a>
    <a href="{% url 'bank:pay-bill' %}">Bill Pay</a>
    <a href="{% url 'bank:service-request' %}">Service Request</a>
    <a href="{% url 'bank:create-account' %}">Create Account</a>
    <a href="{% url 'bank:close-account' %}">Close Account</a>
  </div>

  <div id="title">
    <span class="menu_button" onclick="openNav()">&#9776; Menu</span>
    <span class="site_header">Online Banking System</span>
  </div>

  <script>

  </script>
<div class="clear"></div>
{% block body %}
{% endblock %}<br>
<!-- Page footer. Consistent across all the pages in the website -->
<footer class="page_footer">
		 &copy; Copyright IFB299 2017
</footer>
</body>

</html>

homeApp/templates/home/index.html
{% extends 'home/header.html' %}
{% block title %}Welcome Page{% endblock %}
{% block body %}
<div class="main_content" id="main_content">
  <h1 class="welcome_message"> Welcome to Our</h1>
  <h1 class="welcome_message"> Online Bank Account Access System</h1>
  <br>
  <h4 class="welcome_message"> Please select a Menu option to continue</h4>
</div>
<div class="clear"></div>
{% endblock %}